### ISSUE TITLE
Support a floating 'latest' URL that always points to the latest docs 

### ISSUE THREAD

**Issue by abuehrle** [weaveworks/wordepress#23]
I link to the net docs from the guides, so there needs to be a URL that won't change with the latest release.  I suggest that we make the URLs map to the github tag for latest release.  This means the URL should look something like this: 

documentation/latest_release/using-weave/deploying-applications/

and when archived will revert to: 

documentation/net_1.5/using-weave/deploying-applications/

**Comment by awh** [comment]
Fixed in v1.0.0
